### ISSUE TITLE
[DOC] Update README to align with rest of RAPIDS formatting/flow

### ISSUE THREAD

**Issue by BartleyR** [rapidsai/clx#112]
**Report needed documentation**
Change the README of CLX to more closely match the other RAPIDS readme files. This is a continuation of [PR105](https://github.com/rapidsai/clx/pull/105).

**Comment by BartleyR** [comment]
Reopening

**Comment by msadang** [comment]
Issue has been completed with this PR https://github.com/rapidsai/clx/pull/373.
