### ISSUE TITLE
[BUG] Performance issues from Pytorch for CUDA 10.2

### ISSUE THREAD

**Issue by efajardo-nv** [rapidsai/clx#126]
Pytorch does not officially support CUDA 10.2. CLX is currently using a source build that is causing performance issues with the build and all CLX features using PyTorch/CUDA 10.2.

**Comment by efajardo-nv** [comment]
The DGA Detector unit test has therefore been removed until PyTorch officially releases CUDA 10.2 support. Once 10.2 support is released, unit tested will be added back in.

**Comment by BartleyR** [comment]
This also will impact cyBERT due to the PyTorch dependency there as well. @raykallen

**Comment by raykallen** [comment]
The cyBERT class unit test is dependent on PyTorch as well and needs to be added back once 10.2 support is released.

**Comment by efajardo-nv** [comment]
Add back unit tests for GPU BERT tokenizer when PyTorch with CUDA 10.2 support is released.

**Comment by BartleyR** [comment]
@efajardo-nv Looks like PyTorch now has CUDA 10.2 support. https://pytorch.org/get-started/locally/

**Comment by efajardo-nv** [comment]
Closed by #159
