### ISSUE TITLE
[DOC] Update API Documentation Link

### ISSUE THREAD

**Issue by brhodes10** [rapidsai/clx#162]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/rapidsai/clx/blob/branch-0.14/README.md
This line: `For additional examples, browse our complete API documentation`

**Describe the problems or issues found in the documentation**
The link `API documentation` is pointing to our old doc location https://rapidsai.github.io/clx/ instead of https://docs.rapids.ai/api/clx/nightly/api.html

**Steps taken to verify documentation is incorrect**
Clicked link in README

**Suggested fix for documentation**
Update link to https://docs.rapids.ai/api/clx/nightly/api.html

**Comment by efajardo-nv** [comment]
This will be fixed in PR #160.
