### ISSUE TITLE
[BUG] Torch is not available in Docker image but used in CLX sample notebooks

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/clx#183]
**Describe the bug**
Torch is not installed in rapidsai/rapidsai image.

**Steps/Code to reproduce bug**
1. Start rapidsai docker container
2. Got to `localhost:8888`
3. Navigate to `clx\cybert\cybert_example_training.ipynb`
4. Execute import cell

**Expected behavior**
All imports are loaded.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of CLX install: Docker

**Environment details**
Please run and paste the output of the `/rapids/cudf/print_env.sh` script here, to gather any other relevant environment details. The script is located in the docker container.

            **Another bug**: the `/rapids/cudf` folder no longer exists in the container thus I cannot run the `print_env.sh`.

**Additional context**
This issue was reported in April: [](https://github.com/rapidsai/docker/issues/74)

**Comment by BartleyR** [comment]
This is a known issue. PyTorch 1.5 has a hard dependency on `mkl`, and the RAPIDS container uses the `nomkl` package to prevent installation of this. @efajardo-nv is working on deploying a separate CLX container that solves this short term. We’re also working on removing PyTorch as a hard dependency.

**Comment by drabastomek** [comment]
Thanks @BartleyR! Glad to hear you're seeing this too. I was quite surprised seeing this yesterday when I tried to run CLX from within the container.

**Comment by efajardo-nv** [comment]
@drabastomek The `rapidsai` and `rapidsai-nightly` images don't include CLX. You would have to either `conda install` or build from source on those containers. I just tested this on `rapidsai/rapidsai:0.14-cuda10.1-runtime-ubuntu18.04-py3.7`. You could then install CLX using:

```conda install -c rapidsai -c nvidia -c pytorch -c conda-forge -c defaults clx```

You would then have to install the dependencies for the notebook you want to run. For the cybert notebook, I had to install `pytorch-transformers` and `seqeval`:

`pip install pytorch-transformers seqeval[gpu]`

As @BartleyR mentioned, we're working on CLX Docker images which will have everything working out of the box.

**Comment by drabastomek** [comment]
@efajardo-nv Thanks for the reply -- I will install from `conda`. It is, however, a bit misleading to put the notebooks for clx if the `clx` nor `torch` modules are not included.

**Comment by BartleyR** [comment]
> @efajardo-nv Thanks for the reply -- I will install from `conda`. It is, however, a bit misleading to put the notebooks for clx if the `clx` nor `torch` modules are not included.

Yeah, you’re right. We will make that more clear/straightforward or look at removing and moving.

**Comment by BartleyR** [comment]
@drabastomek We're going to address this with a CLX image which will have all the dependencies. https://github.com/rapidsai/clx/issues/201

**Comment by drabastomek** [comment]
Awesome! Looking forward to testing it.
