### ISSUE TITLE
[BUG] Errors in Alert Analysis Notebook

### ISSUE THREAD

**Issue by efajardo-nv** [rapidsai/clx#199]
**Describe the bug**
When running the CLX Alert Analysis notebook, the following error occurs from the `normalize_gdf` function in the `Heatmap Visualization` section:

```
TypeError: Series object is not iterable. Consider using `.to_arrow()`, `.to_pandas()` or `.values_host` if you wish to iterate over the values.
```
After following suggestion in error, this error occurs in the `cuXfilter` section:
```
NvvmError: Failed to compile

<unnamed> (202, 17): parse expected binary operation in atomicrmw
NVVM_ERROR_COMPILATION
```
**Environment overview**
 - Environment location: Docker container
 - Method of CLX install: conda, Docker, and from source

**Comment by AjayThorve** [comment]
I recently faced this issue too, seems like this is a numba version 0.50.1 issue with datashader, this should be fixed in the numba(0.51), meanwhile, a quick fix would be to downgrade numba to 0.49.1
