### ISSUE TITLE
[DOC] README.md RAPIDS icon 404

### ISSUE THREAD

**Issue by wbadart** [rapidsai/clx#204]
## Report incorrect documentation

**Location of incorrect documentation**
README.md:1, https://github.com/rapidsai/clx/blob/branch-0.15/README.md#cyber-log-accelerators-clx

**Describe the problems or issues found in the documentation**
Looks like someone reorganized the static web assets so https://rapids.ai/assets/images/rapids_logo.png doesn't exist anymore. Not sure where the new asset location is.

**Comment by efajardo-nv** [comment]
Closed by https://github.com/rapidsai/rapids.ai/pull/123.
