### ISSUE TITLE
[FEA] Rename BERT vocab and hash file names for disambiguation

### ISSUE THREAD

**Issue by raykallen** [rapidsai/clx#207]
**Is your feature request related to a problem? Please describe.**
current naming of bert-base-uncased files in the resources folder are `bert_hash_table.txt` and `bert_vocab.txt`

**Describe the solution you'd like**
For disambiguation these files should be more descriptively renamed to `bert-base-uncased-hash.txt` and `bert-base-uncased-vocab.txt`

**Additional context**
I believe this renaming will affect the tokenizer test and phishing detection

**Comment by BartleyR** [comment]
@efajardo-nv and @gbatmaz, for potential phishing detection changes
