### ISSUE TITLE
[BUG] clx.analytics.tokenizer gives error to sentence length > 500

### ISSUE THREAD

**Issue by colpark** [rapidsai/clx#219]
**Describe the bug**
I am trying to make my own GPU-accelerated tokenizer for genomics domain, and below I use **hash_vocab** from **perfect_hash.py** to build my own hash file, and run the tokenizer. Tokenizer works fine with around 100 words (e.g., len(['A C G T C G T C G ...]) = 100 ), but above certain length, program dies with the following error:

> an illegal memory access was encountered in file /opt/conda/envs/rapids/conda-bld/libclx_1597848371306/work/cpp/src/wordPieceTokenizer.cu at line 357

I assured that I have enough GPU memory left. I have installed clx with anaconda, and the versions are new. Using GPU: v100-sxm2-32gb.

**Steps/Code to reproduce bug**
```python
import itertools
from clx.analytics import tokenizer
import cudf

def make_nmer(n):
    """
    Make a word dictionary for sequence base n-gram. Number of word is 4**n
    return word2idx: a dictionary converting a unique n-gram base word to the unique idx
    return wordall: a list containing all possible combinations
    - Example: word2idx, idx2word, wordall = make_nmer(4)
    """
    print('Processing with {} words...'.format(n))
    bases = 'ACGT'
    # Get all possible combination of
    special_tokens = ['[UNK]', '[CLS]', '[SEP]']
    wordall = special_tokens+[''.join(p) for p in itertools.product(bases, repeat=n)]
    wordall.sort()
    word2idx, idx2word = {}, {}
    
    
    for i, nmer in enumerate(wordall):
        word2idx[nmer] = i
        idx2word[i] = nmer
    print('All possible word for {}-gram is {}'.format(n, len(wordall)))
    return word2idx, idx2word, wordall

# Making my own dictionary and vocab list
_,_,wordall=make_nmer(1) 
word_txt='\n'.join(wordall)

# For replication, please set the path for saving the vocab list / and hash file, respectively
word_dir = '<set your path>'
hash_dir = '<set your path>'

# Saving the vocab to fit for the hash_vocab function
with open(word_dir, 'w') as f:
     f.write(word_txt)
hash_vocab(word_dir, hash_dir, compact=False)



# Create some example data that has three sequences with a fixed lengths of wordlen *4
wordlen = 500
example_data = cudf.Series(['A C G T '*wordlen,
                            'A C G T '*wordlen,
                            'A C G T '*wordlen])

tensor, attention_mask, meta_data = tokenizer.tokenize_df(example_data, hash_file=hash_dir, max_sequence_length=wordlen*4, 
                                              stride=50, do_lower=False, do_truncate=False, max_num_sentences=4, 
                                              max_num_chars=10000, max_rows_tensor=10)
```

**Expected behavior**
It should return tokenized tensor with the pattern of [0,1,2,3,0,1,2,3....]

**Environment overview (please complete the following information)**
 - Method of CLX install: [conda]

**Environment details**
<details><summary>Click here to see environment details</summary><pre>

     **git***
     Not inside a git repository

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=16.04
     DISTRIB_CODENAME=xenial
     DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
     NAME="Ubuntu"
     VERSION="16.04.6 LTS (Xenial Xerus)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 16.04.6 LTS"
     VERSION_ID="16.04"
     HOME_URL="http://www.ubuntu.com/"
     SUPPORT_URL="http://help.ubuntu.com/"
     BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
     VERSION_CODENAME=xenial
     UBUNTU_CODENAME=xenial
     Linux nipa2020-0929 4.4.0-176-generic #206-Ubuntu SMP Fri Feb 28 05:02:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Thu Aug 20 15:49:39 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:00:05.0 Off |                  Off |
     | N/A   32C    P0    43W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM2...  On   | 00000000:00:06.0 Off |                  Off |
     | N/A   35C    P0    43W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM2...  On   | 00000000:00:07.0 Off |                  Off |
     | N/A   31C    P0    42W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                24
     On-line CPU(s) list:   0-23
     Thread(s) per core:    1
     Core(s) per socket:    24
     Socket(s):             1
     NUMA node(s):          1
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 85
     Model name:            Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz
     Stepping:              4
     CPU MHz:               2200.112
     BogoMIPS:              4400.22
     Hypervisor vendor:     Xen
     Virtualization type:   full
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              1024K
     L3 cache:              19712K
     NUMA node0 CPU(s):     0-23
     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt clwb xsaveopt xsavec xgetbv1 pku md_clear flush_l1d

     ***CMake***

     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
     Copyright (C) 2015 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Sat_Aug_25_21:08:01_CDT_2018
     Cuda compilation tools, release 10.0, V10.0.130

     ***Python***
     /home/ubuntu/anaconda3/envs/py3clx/bin/python
     Python 3.8.5

     ***Environment Variables***
     PATH                            : /home/ubuntu/anaconda3/envs/py3clx/bin:/home/ubuntu/anaconda3/envs/pytorch_p36/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/cuda/bin
     LD_LIBRARY_PATH                 : /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/lib/:/usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64:/usr/local/cuda-10.0/lib:
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/ubuntu/anaconda3/envs/py3clx
     PYTHON_PATH                     :

     ***conda packages***
     /home/ubuntu/anaconda3/bin/conda
     # packages in environment at /home/ubuntu/anaconda3/envs/py3clx:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                      1_llvm    conda-forge
     abseil-cpp                20200225.2           he1b5a44_2    conda-forge
     arrow-cpp                 0.17.1          py38h1234567_11_cuda    conda-forge
     arrow-cpp-proc            1.0.0                      cuda    conda-forge
     aws-sdk-cpp               1.7.164              hba45d7a_2    conda-forge
     backcall                  0.2.0                     <pip>
     biopython                 1.77                      <pip>
     blas                      2.16                        mkl    conda-forge
     bokeh                     2.1.1            py38h32f6830_0    conda-forge
     boost-cpp                 1.72.0               h7b93d67_2    conda-forge
     boto3                     1.14.45            pyh9f0ad1d_0    conda-forge
     botocore                  1.17.45            pyh9f0ad1d_0    conda-forge
     brotli                    1.0.7             he1b5a44_1004    conda-forge
     brotlipy                  0.7.0           py38h1e0a361_1000    conda-forge
     bzip2                     1.0.8                h516909a_2    conda-forge
     c-ares                    1.16.1               h516909a_0    conda-forge
     ca-certificates           2020.6.20            hecda079_0    conda-forge
     certifi                   2020.6.20        py38h32f6830_0    conda-forge
     cffi                      1.14.1           py38he30daa8_0
     chardet                   3.0.4           py38h32f6830_1006    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     cloudpickle               1.5.0                      py_0    conda-forge
     clx                       0.16.0a200819   py38_g0ae031a_26    rapidsai-nightly
     cryptography              3.0              py38h766eaa4_0    conda-forge
     cudatoolkit               10.1.243             h6bb024c_0    nvidia
     cudf                      0.16.0a200819   cuda_10.1_py38_g08151d9df_1002    rapidsai-nightly
     cudnn                     7.6.0                cuda10.1_0    nvidia
     cugraph                   0.16.0a200819   py38_gcfeddf7b_224    rapidsai-nightly
     cuml                      0.16.0a200819   cuda10.1_py38_gf1f63468e_268    rapidsai-nightly
     cupy                      7.8.0            py38hd239d08_0    conda-forge
     curl                      7.71.1               he644dc0_5    conda-forge
     cytoolz                   0.10.1           py38h516909a_0    conda-forge
     dask                      2.23.0                     py_0    conda-forge
     dask-core                 2.23.0                     py_0    conda-forge
     dask-cudf                 0.16.0a200819   py38_g08151d9df_1002    rapidsai-nightly
     decorator                 4.4.2                     <pip>
     distributed               2.23.0           py38h32f6830_0    conda-forge
     dlpack                    0.3                  he1b5a44_1    conda-forge
     docutils                  0.15.2                   py38_0    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     faiss-proc                1.0.0                      cuda    rapidsai-nightly
     fastavro                  0.24.2           py38h1e0a361_0    conda-forge
     fastrlock                 0.5              py38h950e882_0    conda-forge
     freetype                  2.10.2               he06d7ca_0    conda-forge
     fsspec                    0.8.0                      py_0    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     grpc-cpp                  1.30.2               heedbac9_0    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     icu                       67.1                 he1b5a44_0    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     ipykernel                 5.3.4                     <pip>
     ipython                   7.17.0                    <pip>
     ipython-genutils          0.2.0                     <pip>
     jedi                      0.17.2                    <pip>
     jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
     jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
     joblib                    0.16.0                     py_0    conda-forge
     jpeg                      9d                   h516909a_0    conda-forge
     jupyter-client            6.1.6                     <pip>
     jupyter-core              4.6.3                     <pip>
     krb5                      1.17.1               hfafb76e_2    conda-forge
     lcms2                     2.11                 hbd6801e_0    conda-forge
     ld_impl_linux-64          2.33.1               h53a641e_7
     libblas                   3.8.0                    16_mkl    conda-forge
     libcblas                  3.8.0                    16_mkl    conda-forge
     libclx                    0.16.0a200819   cuda10.1_g0ae031a_26    rapidsai-nightly
     libcudf                   0.16.0a200819   cuda10.1_g08151d9df_1002    rapidsai-nightly
     libcugraph                0.16.0a200819   cuda10.1_gcfeddf7b_224    rapidsai-nightly
     libcuml                   0.16.0a200819   cuda10.1_gf1f63468e_268    rapidsai-nightly
     libcumlprims              0.15.0a200812       cuda10.1_61    rapidsai-nightly
     libcurl                   7.71.1               hcdd3856_5    conda-forge
     libedit                   3.1.20191231         h14c3975_1
     libev                     4.33                 h516909a_0    conda-forge
     libevent                  2.1.10               hcdb4288_1    conda-forge
     libfaiss                  1.6.3           he68dc02_1_cuda    conda-forge
     libffi                    3.3                  he6710b0_2
     libgcc-ng                 9.3.0               h24d8f2e_15    conda-forge
     libgfortran-ng            7.5.0               hdf63c60_15    conda-forge
     libhwloc                  2.1.0                h3c4fd83_0    conda-forge
     libiconv                  1.16                 h516909a_0    conda-forge
     liblapack                 3.8.0                    16_mkl    conda-forge
     liblapacke                3.8.0                    16_mkl    conda-forge
     libllvm10                 10.0.1               he513fc3_1    conda-forge
     libnghttp2                1.41.0               hab1572f_1    conda-forge
     libpng                    1.6.37               hed695b0_2    conda-forge
     libprotobuf               3.12.4               h8b12597_0    conda-forge
     librmm                    0.16.0a200819   cuda10.1_g466b8ed_255    rapidsai-nightly
     libssh2                   1.9.0                hab1572f_5    conda-forge
     libstdcxx-ng              9.1.0                hdf63c60_0
     libtiff                   4.1.0                hc7e4089_6    conda-forge
     libwebp-base              1.1.0                h516909a_3    conda-forge
     libxml2                   2.9.10               h68273f3_2    conda-forge
     llvm-openmp               10.0.1               hc9558a2_0    conda-forge
     llvmlite                  0.34.0           py38h4f45e52_0    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.2                he1b5a44_2    conda-forge
     markupsafe                1.1.1            py38h1e0a361_1    conda-forge
     mkl                       2020.2                      256    conda-forge
     msgpack-python            1.0.0            py38hbf85e49_1    conda-forge
     nccl                      2.7.8.1              h51cf6c1_0    conda-forge
     ncurses                   6.2                  he6710b0_1
     ninja                     1.10.1               hbf85e49_0    conda-forge
     numba                     0.51.0           py38hc5bc63f_0    conda-forge
     numpy                     1.19.1           py38h8854b6b_0    conda-forge
     olefile                   0.46                       py_0    conda-forge
     openssl                   1.1.1g               h516909a_1    conda-forge
     packaging                 20.4               pyh9f0ad1d_0    conda-forge
     pandas                    1.0.5            py38hcb8c335_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.7.1                     <pip>
     partd                     1.1.0                      py_0    conda-forge
     pexpect                   4.8.0                     <pip>
     pickleshare               0.7.5                     <pip>
     pillow                    7.2.0            py38h9776b28_1    conda-forge
     pip                       20.2.2                     py_0    conda-forge
     prompt-toolkit            3.0.6                     <pip>
     psutil                    5.7.2            py38h1e0a361_0    conda-forge
     ptyprocess                0.6.0                     <pip>
     pyarrow                   0.17.1          py38h1234567_11_cuda    conda-forge
     pycparser                 2.20               pyh9f0ad1d_2    conda-forge
     Pygments                  2.6.1                     <pip>
     pyopenssl                 19.1.0                     py_1    conda-forge
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pysocks                   1.7.1            py38h32f6830_1    conda-forge
     python                    3.8.5                hcff3b4d_0
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.8                      1_cp38    conda-forge
     pytorch                   1.6.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
     pytz                      2020.1             pyh9f0ad1d_0    conda-forge
     pyyaml                    5.3.1            py38h1e0a361_0    conda-forge
     pyzmq                     19.0.2                    <pip>
     re2                       2020.07.06           he1b5a44_1    conda-forge
     readline                  8.0                  h7b6447c_0
     regex                     2020.7.14        py38h1e0a361_0    conda-forge
     requests                  2.24.0             pyh9f0ad1d_0    conda-forge
     rmm                       0.16.0a200819   cuda_10.1_py38_g466b8ed_255    rapidsai-nightly
     s3transfer                0.3.3            py38h32f6830_1    conda-forge
     sacremoses                0.0.43             pyh9f0ad1d_0    conda-forge
     scikit-learn              0.23.2           py38hee58b96_0    conda-forge
     scipy                     1.5.2            py38h8c5af15_0    conda-forge
     setuptools                49.6.0           py38h32f6830_0    conda-forge
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sqlite                    3.32.3               h62c20be_0
     tblib                     1.6.0                      py_0    conda-forge
     threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
     thrift-cpp                0.13.0               h62aa4f2_3    conda-forge
     tk                        8.6.10               hbc83047_0
     toolz                     0.10.0                     py_0    conda-forge
     torchvision               0.7.0                py38_cu101    pytorch
     tornado                   6.0.4            py38h1e0a361_1    conda-forge
     tqdm                      4.48.2             pyh9f0ad1d_0    conda-forge
     traitlets                 4.3.3                     <pip>
     transformers              2.1.1                      py_0    conda-forge
     treelite                  0.92             py38h4e709cc_2    conda-forge
     typing_extensions         3.7.4.2                    py_0    conda-forge
     ucx                       1.8.1+g6b29558       ha5db111_0    rapidsai-nightly
     ucx-py                    0.16.0a200819+g6b29558         py38_75    rapidsai-nightly
     urllib3                   1.25.10                    py_0    conda-forge
     wcwidth                   0.2.5                     <pip>
     wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
     xz                        5.2.5                h7b6447c_0
     yaml                      0.2.5                h516909a_0    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zlib                      1.2.11               h7b6447c_3
     zstd                      1.4.5                h6597ccf_2    conda-forge

</pre></details>

**Comment by BartleyR** [comment]
We recently moved the subword tokenizer from CLX to cuDF (https://github.com/rapidsai/cudf/pull/5511), where it's now a cuDF function that can be called on a cuDF Series. In doing so, we patched a number of things and improved the performance. We're also removing the 500 character limit (https://github.com/rapidsai/cudf/pull/5919). Using the new cuDF version of the tokenizer is very similar, and here is a notebook where we use it: https://github.com/rapidsai-community/notebooks-contrib/blob/branch-0.14/conference_notebooks/KDD_2020/notebooks/cybert/cyBERT_training_inference.ipynb. There is a slight change in what it returns ([API ref](https://docs.rapids.ai/api/cudf/nightly/api.html?highlight=subword#cudf.core.column.string.StringMethods.subword_tokenize)).

**Comment by BartleyR** [comment]
@colpark Just curious if you were able to test the tokenizer now that it's in cuDF and if you're still running into issues.

**Comment by BartleyR** [comment]
@colpark We're going to close this issue. If you're still having trouble or there is something else happening, please feel free to open a new issue and we're happy to take a look.
