### ISSUE TITLE
how to mount external notebooks and data

### ISSUE THREAD

**Issue by robomotic** [rapidsai/clx#260]
Hi there,
I would like to know what's the best way to mount an external folder where I have existing notebooks and data.
If I do this

```
docker run  --gpus all \
  --rm -it \
  -p 8888:8888 \
  -p 8787:8787 \
  -p 8686:8686 \
  -v /home/jupyter/mywork:/rapids/clx/mywork \
  clx:latest

```

I can see the folder and notebooks in the Jupyter Lab but I can't modify them (read only).
I am guessing there are some flags or setting to change but not sure how.

Cheers.

**Comment by efajardo-nv** [comment]
Hi. This was a recent issue with the rapidsai images which the clx image is based on. JupyterLab server was being started by the `rapids` user in the container. This user will not have write access to the external folder unless you chmod it to add write permissions to others.

The rapidsai images were updated last night to start JupyterLab with root which would resolve your problem. You would just have to pull the latest nightly image and rebuild your clx image.

**Comment by robomotic** [comment]
Ohhh that makes sense, I am going to test it tomorrow and close the ticket if works.
Thanks.

**Comment by BartleyR** [comment]
Hey @robomotic , just curious if this ended up working for you.

**Comment by robomotic** [comment]
Closing this for now, will re-open after testing if appropriate. Thanks!
