### ISSUE TITLE
[DOC] Update CLX Tokenizer Docs to Reflect Deprecation 

### ISSUE THREAD

**Issue by BartleyR** [rapidsai/clx#274]
The subword tokenizer in CLX is deprecated and will be removed in future releases. This should be updated in the docs.

**Location of incorrect documentation**
https://docs.rapids.ai/api/clx/nightly/api.html?highlight=tokenize#module-clx.analytics.tokenizer
https://docs.rapids.ai/api/clx/nightly/api.html?highlight=tokenize#clx.analytics.tokenizer.tokenize_file

**Describe the problems or issues found in the documentation**
Update documentation to reflect deprecation and point to cuDF subword tokenizer at: https://docs.rapids.ai/api/cudf/nightly/api.html?highlight=subword#cudf.core.column.string.StringMethods.subword_tokenize

**Comment by efajardo-nv** [comment]
PR #283 removed subword tokenizer has been removed from CLX.
