### ISSUE TITLE
[FEA] Multi-class sequence classifier

### ISSUE THREAD

**Issue by raykallen** [rapidsai/clx#333]
**Is your feature request related to a problem? Please describe.**
I want to use the sequence classifier to classify sequences with more than two classes
It currently only supports binary classification (eg. phishing, non-phishing)

**Describe the solution you'd like**
Training and inference for more than two mutually exclusive classes (cat, dog, bird)

**Comment by BartleyR** [comment]
Still needed, keeping this issue open
