### ISSUE TITLE
[DOC] README sample code error

### ISSUE THREAD

**Issue by skiyuki** [rapidsai/clx#414]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/rapidsai/clx#getting-started-with-python-and-notebooks

**Describe the problems or issues found in the documentation**
  python ana_orig.py
  Traceback (most recent call last):
  File "ana_orig.py", line 43, in <module>
    alerts_per_day_piv = pivot_table(day_rule_gdf, 'day', 'rule', 'count').fillna(0)
  File "ana_orig.py", line 35, in pivot_table
    for group in gdf[piv_col].unique():
  File "/opt/miniconda3/envs/myenv/lib/python3.7/site-packages/cudf/core/frame.py", line 3373, in __iter__
    cudf.utils.utils.raise_iteration_error(obj=self)
  File "/opt/miniconda3/envs/myenv/lib/python3.7/site-packages/cudf/utils/utils.py", line 212, in raise_iteration_error
    f"{obj.__class__.__name__} object is not iterable. "
TypeError: Series object is not iterable. Consider using `.to_arrow()`, `.to_pandas()` or `.values_host` if you wish to iterate over the values.
Condition:
  ana_orig.py: copy pasted from README
  cudf: 0.19.2
  Python: Python 3.7.10 (default, Feb 26 2021, 18:47:35)
  OS: Ubuntu 20.04

**Steps taken to verify documentation is incorrect**
Pandas.Series.unique() returns ndarray or ExtensionArray.
Cudf.core.series.Series.unique() returns Series.

**Suggested fix for documentation**
  Change "for group in gdf[piv_col].unique():" to
  correct codes such as the following:
  s_ = gdf[piv_col].unique()
  for i_ in range(len(s_)):
    group = s_[i_]

-

**Comment by efajardo-nv** [comment]
@skiyuki Thank you for catching this!

**Comment by skiyuki** [comment]
Prefer to_pandas()
Running the "for i_ in range(len(s_)):" generates 161 DEBUG messages from Numba, which indicates
CPU->GPU->CPU jumping loops, increases running time.
Adding "to_pandas()" to the original code generates no DEBUG messages, decrece running time from 0.55 to 0.3 at Intel 3GHz + GTX1060.

I would use to_pandas() in my estimation.

Messages are obtained:
```python
import logging # Instered
logger = logging.getLogger() # Instered
def pivot_table(gdf, index_col, piv_col, v_col):
    index_list = gdf[index_col].unique()
    piv_gdf = cudf.DataFrame()
    piv_gdf[index_col] = index_list
    logging.basicConfig(level=logging.DEBUG) # Instered
    logger.info('Start') # Instered
    #for group in gdf[piv_col].unique().to_pandas():
    s_ = gdf[piv_col].unique() # Instered
    for i_ in range(len(s_)): # Changed
        group = s_[i_] # Instered
        temp_df = gdf[gdf[piv_col] == group]
        temp_df = temp_df[[index_col, v_col]]
        temp_df.columns = [index_col, group]
        piv_gdf = piv_gdf.merge(temp_df, on=[index_col], how='left')
    logger.info('End') # Instered
    logging.disable(logging.DEBUG) # Instered
    piv_gdf = piv_gdf.set_index(index_col)
    return piv_gdf.sort_index()
```
