### ISSUE TITLE
[FEA] Update notebooks to use the new Tokenizer

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/clx#418]
**Is your feature request related to a problem? Please describe.**

We should update the log parsing notebooks to use the new [API](https://docs.rapids.ai/api/cudf/nightly/api.html?highlight=subword_tokenize#cudf.core.subword_tokenizer.SubwordTokenizer.__call__) as its much faster (13x) and cleaner to use. 

Happy to take this one.

**Comment by BartleyR** [comment]
@VibhuJawa Sounds great, go for it
