### ISSUE TITLE
[BUG] clx docker incorrectly pulls in CPU pytorch

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/clx#429]
**Describe the bug**

The latest docker image (see below) , has torch-cpu installed instead of pytorch gpu. 
```bash
docker pull rapidsai/rapidsai-clx-nightly:21.06-cuda11.0-runtime-ubuntu18.04-py3.7
```

**Steps/Code to reproduce bug**

Inside the docker container do below:
```python
(rapids) root@5344304a4dbe:/rapids# python3
>>> import torch
>>> torch.cuda.is_available()
False
```

```bash
(rapids) root@5344304a4dbe:/rapids# conda list | grep torch
pytorch                   1.7.1           cpu_py37hf1c21f6_2    conda-forge
torchvision               0.2.2                      py_3    pytorch

```

**Expected behavior**
I expect Pytorch GPU  to be installed.

**Comment by VibhuJawa** [comment]
@efajardo-nv, I think adding `cudnn=8.0` might fix this issue.   


```
mamba install -c rapidsai-nightly -c nvidia -c pytorch -c conda-forge clx cudnn=8.0 
```

I think pytorch=1.7.1 has builds that rely on `cudnn` to be present. 
For context look at the package build name on their  conda channel. 
See link: 

https://anaconda.org/pytorch/pytorch/1.7.1/download/linux-64/pytorch-1.7.1-py3.8_cuda11.0.221_cudnn8.0.5_0.tar.bz2

**Comment by VibhuJawa** [comment]
> @efajardo-nv, I think adding `cudnn=8.0` might fix this issue.
> 
> ```
> mamba install -c rapidsai-nightly -c nvidia -c pytorch -c conda-forge clx cudnn=8.0 
> ```
> 
> I think pytorch=1.7.1 has builds that rely on `cudnn` to be present.
> For context look at the package build name on their conda channel.
> See link:
> 
> https://anaconda.org/pytorch/pytorch/1.7.1/download/linux-64/pytorch-1.7.1-py3.8_cuda11.0.221_cudnn8.0.5_0.tar.bz2


Let me confirm if stuff works if I do the installation like this.

**Comment by efajardo-nv** [comment]
@VibhuJawa Since v21.06 is now the stable release, we would have to pull that image from `rapidsai/rapidsai-clx` and not `rapidsai/rapidsai-clx-nightly` as the README indicates. If you pull from `rapidsai/rapidsai-clx`, your container should have the CUDA version of PyTorch installed in the default `rapids` conda environment.
```
docker pull rapidsai/rapidsai-clx:21.06-cuda11.0-runtime-ubuntu18.04-py3.7
```

A [PR](https://github.com/rapidsai/clx/pull/432) has been created that includes correction to `docker pull` command in README.
