### ISSUE TITLE
[FEA] DGA train_model function

### ISSUE THREAD

**Issue by brhodes10** [rapidsai/clx#92]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Requesting to remove the second parameter `dataset_len` from the function below in `dga_detector`. And calculate `dataset_len` within the `train_model` function instead.

`def train_model(self, partitioned_dfs, dataset_len)`

**Describe alternatives you've considered**
Calculate `dataset_len` prior to calling `train_model`

**Comment by bsuryadevara** [comment]
Added requested changes to [PR#103](https://github.com/rapidsai/clx/pull/103)
