### ISSUE TITLE
[FEA] Add Bokeh visualization back to Alert Analysis notebook

### ISSUE THREAD

**Issue by BartleyR** [rapidsai/clx#93]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. Adding back features to a notebook.

**Describe the solution you'd like**
Add the Bokeh visualizations back to the alert analysis notebook to provide options to users and demonstrate the ease of going to the CPU if necessary. Just showing the capability should be sufficient (e.g., a few visualizations).

**Comment by raykallen** [comment]
Added in and merged in PR 96 [https://github.com/rapidsai/clx/pull/96]
