### ISSUE TITLE
[FEA] DGA Detector - string2ascii and train_model

### ISSUE THREAD

**Issue by brhodes10** [rapidsai/clx#94]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently `train_model` function requires the user to convert the input dataframe containing column of domains from string2ascii

Requesting that `train_model` function convert input dataframe to ascii

**Describe alternatives you've considered**
Alternative is for user to convert data from string2ascii using `string2ascii` function within DGADetector

**Additional context**

**Comment by bsuryadevara** [comment]
Added requested changes to [PR#103](https://github.com/rapidsai/clx/pull/103)
